### ISSUE TITLE
Issue with language stats bar

### ISSUE THREAD

**Issue by DecimalTurn** [ReneNyffenegger/VBAModules#1]
Currently, the GitHub stats bar for this repo doesn't even include VBA:

![image](https://github.com/ReneNyffenegger/VBAModules/assets/31558169/2a125696-6f61-4c2e-8b68-c0938987e436)

This is partially because none of the files contain any of the normal metadata that appears at the top of VBA files when they are exported via the VBE. For example, when a module is exported to a .bas file with the VBE, it will include the following metadata at the top of the file:
```
Attribute VB_Name = "ModuleName"
```

One way to fix this issue would be to add this metadata manually or via a script, but if you don't want to bother with that and just fix the stats bar, you could add a `.gitattributes` file with the following lines to your repo:

```gitattributes

*.bas linguist-language=vba
*.cls linguist-language=vba
*.frm linguist-language=vba

```

This will serve to override those files extensions to make sure they are counter as VBA in the stats bar. Let me know if you'd prefer me to make a PR for that.

**Comment by ReneNyffenegger** [comment]
Thanks for the recommendation - I didn't know about linguist-language in .gitattributes.

Your suggestion is implemented with https://github.com/ReneNyffenegger/VBAModules/commit/cbb7c22fff8f3cd66543cfcd4bd69039db9acfa6

**Comment by DecimalTurn** [comment]
My pleasure! I'll let you decide if you want to do the same for you other VBA repos such as:
* https://github.com/ReneNyffenegger/about-VBA 
* https://github.com/ReneNyffenegger/VBA-SwapKeys

Also, I see that some .vb file might contain VBA code, am I mistaken?

**Comment by ReneNyffenegger** [comment]
Thanks again - I postboned doing this for way too long and have finally done it today!
And yes: .vb files contain VBA code. I have switched from using .bas to .vb as preferred suffix for a reason that had to do with syntax highlighting in a specific editor (I believe)

**Comment by DecimalTurn** [comment]
No worries, thanks for providing theses ressources. Just curious what is the name of the editor in question?

Also, my list was not exhaustive it seems. There are still a few repos with the same issue:
* https://github.com/ReneNyffenegger/VBA-calls-DLL
* https://github.com/ReneNyffenegger/runVBAFilesInOffice
* https://github.com/ReneNyffenegger/VBA-Task-Automator
* https://github.com/ReneNyffenegger/temp-VBA-callback-funcs
* https://github.com/ReneNyffenegger/VBA-SetWindowsHookEx
* https://github.com/ReneNyffenegger/temp-PowerPointCreator
* https://github.com/ReneNyffenegger/VBA-set-Azure-Information-Protection-tag
* https://github.com/ReneNyffenegger/runVBAFilesInOffice

**Comment by ReneNyffenegger** [comment]
Oh... there were some repos I successfully managed to forget about - thanks anyway for your effort, much appreciated.
